crm/urls.py
from . import views
from django.urls import path, re_path

app_name = 'crm'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path("register", views.register_request, name="register"),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('service_list', views.service_list, name='service_list'),
    path('service/create/', views.service_new, name='service_new'),
    path('service/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('service/<int:pk>/delete/', views.service_delete, name='service_delete'),
    path('customer/<int:pk>/summary/', views.summary, name='summary'),
    path('product_list', views.product_list, name='product_list'),
    path('product/create/', views.product_new, name='product_new'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('customer/<int:pk>/summary/', views.summary, name='summary'),

]

msfcrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('crm.urls')),
]

crm/models.py
from django.db import models
from django.utils import timezone

#Define the model for the Customer table
class Customer(models.Model):
    cust_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=20)
    bldgroom = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    organization = models.CharField(max_length=100)
    role = models.CharField(max_length=100)

    def __str__ (self):
        return self.cust_name


class Service(models.Model):
    cust_name = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='services')
    service_category = models.CharField(max_length=100)
    description = models.TextField()
    location = models.CharField(max_length=200)
    setup_time = models.DateTimeField(
        default=timezone.now)
    cleanup_time = models.DateTimeField(
        default=timezone.now)
    service_charge = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.cust_name)

class Product(models.Model):
    cust_name = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='products')
    product = models.CharField(max_length=100)
    description = models.TextField()
    quantity = models.IntegerField()
    pickup_time = models.DateTimeField(
        default=timezone.now)
    charge = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.cust_name)

crm/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Customer, Service, Product


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_name', 'organization', 'role', 'bldgroom', 'address', 'city', 'state', 'zipcode',
                  'email', 'phone')


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = (
            'cust_name', 'service_category', 'description', 'location', 'setup_time', 'cleanup_time', 'service_charge')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('cust_name', 'product', 'description', 'quantity', 'pickup_time', 'charge')

crm/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib import messages
from .models import *
from .forms import *
from django.db.models import Sum
from _decimal import Decimal

now = timezone.now()


def home(request):
    return render(request, 'crm/home.html',
                  {'crm': home})


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("crm:home")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="registration/register.html", context={"register_form": form})


@login_required
def customer_list(request):
    customer = Customer.objects.filter()
    return render(request, 'crm/customer_list.html',
                  {'customers': customer})


@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter()
            return render(request, 'crm/customer_list.html',
                          {'customers': customer})
    else:
        # edit
        form = CustomerForm(instance=customer)
    return render(request, 'crm/customer_edit.html', {'form': form})


@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('crm:customer_list')


@login_required
def service_list(request):
    services = Service.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/service_list.html', {'services': services})


@login_required
def service_new(request):
    if request.method == "POST":
        form = ServiceForm(request.POST)
        if form.is_valid():
            service = form.save(commit=False)
            service.created_date = timezone.now()
            service.save()
            services = Service.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/service_list.html',
                          {'services': services})
    else:
        form = ServiceForm()

    return render(request, 'crm/service_new.html', {'form': form})


@login_required
def service_edit(request, pk):
    service = get_object_or_404(Service, pk=pk)
    if request.method == "POST":
        form = ServiceForm(request.POST, instance=service)
        if form.is_valid():
            service = form.save()
            service.updated_date = timezone.now()
            service.save()
            services = Service.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/service_list.html', {'services': services})
    else:
        form = ServiceForm(instance=service)
    return render(request, 'crm/service_edit.html', {'form': form})


@login_required
def service_delete(request, pk):
    service = get_object_or_404(Service, pk=pk)
    service.delete()
    return redirect('crm:service_list')


@login_required
def product_list(request):
    products = Product.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/product_list.html', {'products': products})


@login_required
def product_new(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_date = timezone.now()
            product.save()
            products = Product.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/product_list.html',
                          {'products': products})
    else:
        form = ProductForm()
    # print("Else")
    return render(request, 'crm/product_new.html', {'form': form})


@login_required
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save()
            # product.customer = product.id
            product.updated_date = timezone.now()
            product.save()
            products = Product.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/product_list.html', {'products': products})
    else:
        # print("else")
        form = ProductForm(instance=product)
    return render(request, 'crm/product_edit.html', {'form': form})


@login_required
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    return redirect('crm:product_list')


@login_required
def summary(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    services = Service.objects.filter(cust_name=pk)
    products = Product.objects.filter(cust_name=pk)
    sum_service_charge = \
        Service.objects.filter(cust_name=pk).aggregate(Sum('service_charge'))
    sum_product_charge = \
        Product.objects.filter(cust_name=pk).aggregate(Sum('charge'))

    # if no product or service records exist for the customer,
    # change the ‘None’ returned by the query to 0.00
    sum = sum_product_charge.get("charge__sum")
    if sum == None:
        sum_product_charge = {'charge__sum': Decimal('0')}
    sum = sum_service_charge.get("service_charge__sum")
    if sum == None:
        sum_service_charge = {'service_charge__sum': Decimal('0')}

    return render(request, 'crm/summary.html', {'customer': customer,
                                                'products': products,
                                                'services': services,
                                                'sum_service_charge': sum_service_charge,
                                                'sum_product_charge': sum_product_charge, })


@login_required
def summary(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    services = Service.objects.filter(cust_name=pk)
    products = Product.objects.filter(cust_name=pk)
    sum_service_charge = \
        Service.objects.filter(cust_name=pk).aggregate(Sum('service_charge'))
    sum_product_charge = \
        Product.objects.filter(cust_name=pk).aggregate(Sum('charge'))

    # if no product or service records exist for the customer,
    # change the ‘None’ returned by the query to 0.00
    sum = sum_product_charge.get("charge__sum")
    if sum == None:
        sum_product_charge = {'charge__sum': Decimal('0')}
    sum = sum_service_charge.get("service_charge__sum")
    if sum == None:
        sum_service_charge = {'service_charge__sum': Decimal('0')}

    return render(request, 'crm/summary.html', {'customer': customer,
                                                'products': products,
                                                'services': services,
                                                'sum_service_charge': sum_service_charge,
                                                'sum_product_charge': sum_product_charge, })

crm/templates/crm/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
<!-- jQuery library -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

<!-- add local stylesheet -->
<link rel="stylesheet" href="{% static "css/portfolio.css" %}">


<div class="container-fluid">

    <div class="navbar-header">
        <!-- Branding Image -->
        <a class="navbar-brand" href="">
            Maverick Food Service
        </a>
        <!-- Button to collapse Navbar Button -->
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#myNavbar" aria-controls="myNavbar">
            Toggle Navigation
        </button>
    </div>
    <!-- Dark background with white text -->
    <nav class="navbar navbar-expand-md bg-secondary navbar-dark" id="myNavbar">
        <!--Display navigation options left-justified in navbar -->
        <ul class="navbar-nav mr-auto">
            <li class="navbar-brand"></li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'crm:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'crm:customer_list' %}">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'crm:service_list' %}">Services</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'crm:product_list' %}">Products</a>
            </li>
        </ul>
        <!--Display Login/Logout right-justified in navbar -->
        <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
                </li>

            {% else %}
                <li><a class="nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                </li>
                <li><a class="nav-link" href="{% url 'crm:register' %}"><span class="glyphicon glyphicon-log-in"></span>Register</a>
                </li>
            {% endif %}
        </ul>
    </nav>


</div>
<body id="app-layout">
<div class="row">
    <div class="col-md-8">
        {% block content %}
        {% endblock %}
    </div>
</div>
</div>
</div>
</body>
</html>

crm/templates/crm/customer_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=customer.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

</html>

crm/templates/crm/customer_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
        <style>
        body {background-color: beige;}
    </style>
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}
</html>

crm/templates/crm/customer_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Maverick Food Services</title>
    </head>
    <body class="bodylist">

    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Welcome!</div>
            <div class="panel-body">
                Maverick Food Services, Ingredients For Your Success!.
            </div>
        </div>
    </div>
    <div class="row">
        <h2>Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Name</th>
                <th>Organization</th>
                <th>Role</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Bldg-Room</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_name }}</td>
                    <td>{{ customer.organization }}</td>
                    <td>{{ customer.role }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.phone }}</td>
                    <td>{{ customer.bldgroom }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td><a href="{% url 'crm:customer_edit' pk=customer.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                    <td><a href="{% url 'crm:summary' pk=customer.pk %}"
                           class="btn btn-primary">Summary</a>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

</html>

crm/templates/crm/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load static %}
{% block content %}
    <body>
    {% if user.is_authenticated %}
        <div class="page-container">
            <h2 class="top-menu">Hello {{ user.username }},</h2>
            <p>Please choose from options below.</p>
        </div>
    {% else %}
        <p>Please choose from options below.</p>
    {% endif %}
    <div class="content container">
        <!-- Example row of columns using cards for alignment
             The value of 'col-md-x' for all columns in the row must add up to 12
             This page has 3 columns, each column uses col-md-4, for a total of 12 -->
        <div class="row">
            <div class="col-md-4 d-flex align-items-stretch">
                <div class="card">
                    <img src="{% static "images/customer.jpg" %}" class="card-img-top" alt="customer">
                    <div class="card-body">
                        <h5 class="card-title">Customers</h5>
                        <p class="card-text">We love our customers.</p>
                        <p><a class="btn btn-primary" href="{% url 'crm:customer_list' %}"
                              role="button">View details &raquo;</a></p>
                    </div>
                </div>
            </div>

           <div class="col-md-4 d-flex align-items-stretch">
                <div class="card">
                    <img src="{% static "images/lunch.jpeg" %}" class="card-img-top" alt="lunch">
                    <div class="card-body">
                        <h5 class="card-title">Services</h5>
                        <p class="card-text">Great Services</p>
                        <p><a class="btn btn-primary" href="{% url 'crm:service_list' %}"
                              role="button">View details &raquo;</a></p>
                    </div>
                </div>
            </div>
           <div class="col-md-4 d-flex align-items-stretch">
                <div class="card">
                    <img src="{% static "images/cupcakes.jpeg" %}" class="card-img-top" alt="cupcakes">
                    <div class="card-body">
                        <h5 class="card-title">Products</h5>
                        <p class="card-text">Great Products</p>
                        <p><a class="btn btn-primary" href="{% url 'crm:product_list' %}"
                              role="button">View details &raquo;</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
{% endblock %}
</html>

crm/templates/crm/product_delete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block body_block %}
    <h1>Delete {{ product.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk= product.cust_name %} ">Cancel</a>

    </form>

{% endblock %}

</html>

crm/templates/crm/product_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Edit Product</h1>
    <form method="POST" class="product-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

</html>

crm/templates/crm/product_list.html
<!DOCTYPE html>
{% extends 'crm/base.html' %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Maverick Food Services</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Maverick Food Services, Ingredients For Your Success!.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Product Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Name</th>
                <th>Product</th>
                <th>Product Description</th>
                <th>Quantity</th>
                <th>Pickup Time</th>
                <th>Charge</th>
                <th>Created Date</th>
                <th>Updated Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.cust_name }}</td>
                    <td>{{ product.product }}</td>
                    <td>{{ product.p_description }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>{{ product.pickup_time }}</td>
                    <td>{{ product.charge }}</td>
                    <td>{{ product.created_date }}</td>
                    <td>{{ product.updated_date }}</td>
                    <td><a href="{% url 'crm:product_edit' pk=product.pk %}"
                           class="btn btn-warning">Edit</a></td>
                     <td><a href="{% url 'crm:product_delete' pk=product.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                     </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
         <div class="row">
         <a href="{% url 'crm:product_new' %}" class="row"><span
                    class="btn btn-primary">Add Product</span></a>
     </div>

    </body>
{% endblock %}

crm/templates/crm/product_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Add a New Product</h1>
    <form method="POST" class="product-form">{% csrf_token %}
          {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

</html>

crm/templates/crm/service_delete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block body_block %}
    <h1>Delete {{ service.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk= service.cust_number %} ">Cancel</a>

    </form>

{% endblock %}

</html>

crm/templates/crm/service_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <style> body { background-color: beige; } </style>
    <h1>Edit Service</h1>
    <form method="POST" class="service-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}
</html>

crm/templates/crm/service_list.html
<!DOCTYPE html>
{% extends 'crm/base.html' %}
{% block content %}
    {% load humanize %}

    <head>
        <title>Maverick Food service</title>
    </head>
    <body class="bodylist">
    <div class="container">

        <div class="panel panel-primary">
            <div class="panel-heading">Welcome!</div>
            <div class="panel-body">
                Maverick Food Services, Ingredients For Your Success!.
            </div>
        </div>

    </div>
    <div class="row">
        <h2>Services Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Customer</th>
                <th>Service Category</th>
                <th>Description</th>
                <th>Location</th>
                <th>Setup Time</th>
                <th>Cleanup Time</th>
                <th>Service Charge</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for service in services %}
                <tr>
                    <td>{{ service.cust_name }}</td>
                    <td>{{ service.service_category }}</td>
                    <td>{{ service.description }}</td>
                    <td>{{ service.location }}</td>
                    <td>{{ service.setup_time }}</td>
                    <td>{{ service.cleanup_time }}</td>
                    <td>${{ service.service_charge|floatformat:2|intcomma }}</td>
                    <td><a href="{% url 'crm:service_edit' pk=service.pk %}"
       class="btn btn-warning">Edit</a>

                    </td>
                    <td><a href="{% url 'crm:service_delete' pk=service.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

    <div>
<a href="{% url 'crm:service_new' %}"><span
        class="btn btn-primary">Add Service</span></a>


    </div>
    </body>
{% endblock %}

crm/templates/crm/service_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Service</h1>
    <form method="POST" class="service-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}
</html>

crm/templates/crm/summary.html
{% extends 'crm/base.html' %}
{% block content %}
{% load mathfilters %}
{% load humanize %}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Maverick Food services, Ingredients For Your Success!
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
  <h1 style="padding-left: 15Px">Customer Summary for {{ customer.cust_name }}</h1>
</div>
   <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr class="bg-info">
                <th>Total of Services and Product Charges</th>
            </tr>
        </thead>
        <tbody>
            <tr>
               <td id="total_charge">

            </tr>
        </tbody>
    </table>


        <div class="row">
        <h2 style="padding-left: 15Px">Services Information</h2>
    </div>
    <div class="row">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Service Category</th>
                <th>Description</th>
                <th>Location</th>
                <th>Setup Time</th>
                <th>Cleanup Time</th>
                <th>Service Charge</th>

            </tr>
            </thead>
            <tbody>
            {% for service in services %}
                <tr>
                    <td>{{ service.service_category }}</td>
                    <td>{{ service.description }}</td>
                    <td>{{ service.location }}</td>
                    <td>{{ service.setup_time }}</td>
                    <td>{{ service.cleanup_time }}</td>
                    <td>{{ service.service_charge }}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr class="bg-info">
                <th>Total of Service Charges</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td id="service_charge">{{ sum_service_charge.service_charge__sum|intcomma }}</td>

            </tr>
        </tbody>
    </table>
</div>

    <div class="row">
        <h2 style="padding-left: 15Px">Product Information</h2>
    </div>
    <div class="row">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Product</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Pickup Time</th>
                <th>Total Charge</th>

            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.product }}</td>
                    <td>{{ product.p_description }}</td>
                    <td>{{ product.quantity|intcomma }}</td>
                    <td>{{ product.pickup_time }}</td>
                    <td>{{ product.charge|intcomma }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr class="bg-info">
                <th>Total of Product Charges</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td id="product_charge">{{ sum_product_charge.charge__sum|intcomma }}</td>

            </tr>
        </tbody>
    </table>
</div>
{% endblock %}